[mount_point]
/data = /data

[paths]
root_dir = .
data_dir = /data
log_dir = /var/log

[iptv]
work_dir = ./iptv
iptv_data_dir = /data/iptv_data

[news]
work_dir = ./news
news_data_dir = /data/news_data

[crawlers]
spiders_dir = ./crawlers/spiders
xueqiu_data_dir = /data/xueqiu_data
analyst_data_dir = /data/analyst_data

[stock_monitor]
stock_monitor_dir = ./stock_monitor
stock_monitor_data_dir = /data/stock_monitor_data
database_dir = /data/stock_monitor_data/database
settings_file = /data/stock_monitor_data/settings.json
stocks_file = /data/stock_monitor_data/stocks.json

[web_app]
web_template_dir = ./stock_monitor/web_templates
web_static_dir = ./stock_monitor/web_static

[messaging]
message_server = https://message.jgyang.cn:5555
message_username = root
message_token = 12123121
message_channel = wechat

[cache]
stock_cache_timeout = 180
industry_cache_timeout = 86400
analyst_cache_timeout = 86400
index_cache_timeout = 86400
fund_cache_timeout = 86400

; STOCK_CACHE_DURATOIN_SECONDS = get_path('stock_cache_timeout', 3*60)
; INDUSTRY_CACHE_DURATION_SECONDS = get_path('industry_cache_timeout', 24*60*60)
; ANALYST_CACHE_DURATION_SECONDS = get_path('analyst_cache_timeout', 24*60*60)
; INDEX_CACHE_DURATION_SECONDS = get_path('index_cache_timeout', 1*24*60*60)
; FUND_CACHE_DURATION_SECONDS = get_path('fund_cache_timeout', 1*24*60*60)  # 新增基金缓存时长配置
