# This is a default site configuration which will simply return 404, preventing
# chance access to any other virtualhost.

server {
    listen 80 default_server;

    #location / {
    #    root /usr/share/nginx/html;
    #    index index.html;
    #}
    
    location /{
        root /data/blog;
        try_files $uri $uri/ =404;
    }

    location ~^/iptv/(.*\.(m3u|txt))$ {
        alias /data/iptv/$1;                                                                                                                                   
        #add_header Content-Type "application/vnd.apple.mpegurl; charset=utf-8";
        #default_type application/vnd.apple.mpegurl;
        add_header Content-Type "text/plain; charset=utf-8";
        default_type text/plain;
    }
    
	
	# You may need this to prevent return 404 recursion.
	location = /404.html {
		internal;
	}
}

